[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Règle pour permettre l'accès aux fichiers de traduction
[[redirects]]
  from = "/locales/*"
  to = "/locales/:splat"
  status = 200

# Règle générale pour les autres chemins
[[redirects]]
  from = "https://virgilepopote.com/*"
  to = "https://virgile.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://virgilepopote.com/*"
  to = "https://virgile.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.virgilepopote.com/*"
  to = "https://virgile.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.virgilepopote.com/*"
  to = "https://virgile.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
