[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Forcer HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Assurer que les routes de l'API sont correctement gérées
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# Gestion des routes Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200

# Configuration pour gérer les en-têtes de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
